modLoader="javafml"
loaderVersion="[43,44)"
license="MIT"

[[mods]]
modId="tooltime"
version="${file.jarVersion}"
displayName="Tool Time"
authors="SkySom"
description='''Tool Time'''

[[dependencies.tooltime]]
modId="forge"
mandatory=true #mandatory
versionRange="[43.2.0,43.3.0)"
ordering="NONE"
side="BOTH"

[[dependencies.tooltime]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"